### ISSUE TITLE
onmouseover event over a pushpin not working

### ISSUE THREAD

**Issue by deepuabrahamk** [rbrundritt/BingMapsV63ToV8Shim#3]
Hi Ricky,

I have a similar code and I am not able to check if I have hovered over a particular pushpin. The elementID is always null.
map.AttachEvent("onmouseover", onMouseOverCallback);
…
function onMouseOverCallback(e)
{
   // check to see if we have hovered over a pushpin
   if(e.elementID != null)
   {
    // do something
   }
}

Best Regards,
Deepu Abraham K

**Comment by rbrundritt** [comment]
Use the GetId() function. The elementID property was never a documented part of the V6.3 API and you were meant to use the GetId function.
